## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
##
remote: origin
target-branch: main
chart-dirs:
  - charts/
chart-repos:
  - buttahtoast=https://buttahtoast.github.io/helm-charts/
  - bitnami=https://charts.bitnami.com/bitnami
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false